### ISSUE TITLE
German Translation of Your First Game tutorial breaks program

### ISSUE THREAD

**Issue by Ajikeshi85** [godotengine/godot-docs-l10n#10]
Certain Translation errors will lead to unexplained errors when following the "Your First Game" tutorial in german.
Other Translations will lead to much confusion when beginners follow the tutorial

- sometimes the tutorial refers to a Mob-Scene other times to a "Gegner"-Scene (german translation of mob).
This might causes a bit of confusion.
- in the HUD section you are prompted to name the Message Label "MessageLabel" instead of "Message" which is used later in the code and in the english version of this document

Furthermore: the links to the github site in the documentation are incorrect.
They link to https://github.com/godotengine/godot-docs-l10n/blob/stable//getting_started/step_by_step/your_first_game.rst and https://github.com/godotengine/godot-docs-l10n/edit/stable//getting_started/step_by_step/your_first_game.rst which are 404

I submitted suggestions for the correct translations on https://hosted.weblate.org/projects/godot-engine anonymously since i am unsure which route to take to report/correct it.
If necessary i can create a Pull request for the corrections as well.

**Comment by nitramr** [comment]
@Ajikeshi85 I checked the whole section "Das erste Spiel" and fixed a lot of things. It will be available in the online documentation if an admin will sync the latest changes from Weblate.
