### ISSUE TITLE
Godot Class Reference is not translated?

### ISSUE THREAD

**Issue by narrnika** [godotengine/godot-docs-l10n#11]
On Weblate, I see [lines](https://hosted.weblate.org/translate/godot-engine/godot-class-reference/ru/?checksum=53d94fcc071e31b) that were translated 9 months ago (june 2020). That is, they should have been included in both the latest stable build (v3.2.3, september 2020) and the latest update of the web-documentation (96231fc4, january 2021). However, this did not happen. Does this mean that the translation Godot Class Reference is not supported and there is no sense in translating this component?

**Comment by akien-mga** [comment]
The class reference translations are only for the `master` branch (future 4.0), the feature to translate it did not exist in the `3.2` branch. I did not backport it to the `3.2` branch as the translation effort required to get the whole class reference translated will be huge, and I didn't think reasonable to start it *after* the 3.2 release was already out.

In parallel, the `master` branch is still undergoing heavy refactoring work and a lot of the new APIs for 4.0 have yet to be documented, so I haven't synced the `godot-class-reference` Weblate resource in a while. I'm waiting for things to be more stable to do so. I thought about locking it but translations made now might still be relevant for the most part once updated for 4.0 alpha.

**Comment by narrnika** [comment]
> I thought about locking it but translations made now might still be relevant for the most part once updated for 4.0 alpha.

Maybe just mention the target version in the name of the Weblate-components?
