### ISSUE TITLE
Using axis instead of using 4 condition

### ISSUE THREAD

**Issue by Watynecc** [godotengine/godot-docs-l10n#12]
Using this code PS: i use C#
`
velocity.x = Input.GetActionStrength("ui_right") - Input.GetActionStrength("ui_left");
velocity.y = Input.GetActionStrength("ui_down") - Input.GetActionStrength("ui_up");
`
instead of this code

    if (Input.IsActionPressed("ui_right"))
    {
        velocity.x += 1;
    }

    if (Input.IsActionPressed("ui_left"))
    {
        velocity.x -= 1;
    }

    if (Input.IsActionPressed("ui_down"))
    {
        velocity.y += 1;
    }

    if (Input.IsActionPressed("ui_up"))
    {
        velocity.y -= 1;
    }

Why : 
It does the same result for less line
More easy to eat it (When learn Godot)
More minimal UwU

**Comment by akien-mga** [comment]
This repository is for the localization of the Godot documentation, not for user support. See [Godot community platforms](https://godotengine.org/community/) for support.
