### ISSUE TITLE
Chinese strings have more than 200 lines less than English and other languages.

### ISSUE THREAD

**Issue by magian1127** [godotengine/godot-docs-l10n#13]
![image](https://user-images.githubusercontent.com/14800320/120913412-adb55380-c6c9-11eb-942c-3e4f2116686f.png)

![image](https://user-images.githubusercontent.com/14800320/120913424-ba39ac00-c6c9-11eb-8ed9-384e2913c7f8.png)

中文字符串比英语和其他语言少了200多行.

Chinese strings have more than 200 lines less than English and other languages.

**Comment by akien-mga** [comment]
Thanks for the report, I can confirm the issue. I'll check what it means concretely, maybe there's something in the zh_CN translation which breaks the parser.

**Comment by DeeJayLSP** [comment]
@akien-mga I would like to report that the very same issue also happens with pt_BR

**Comment by akien-mga** [comment]
I checked the files in the Git repo, and downloaded the generated PO files from Weblate, and in both cases the strings count is displayed correctly by Poedit:
![Screenshot_20210608_111432](https://user-images.githubusercontent.com/4701338/121158513-b719f980-c84a-11eb-9a06-7acee46d9d70.png)

Here are some examples of the strings that Weblate seemed to fail including (at least in the zh_CN translation, I can find them by checking the 282 not translated strings in the PO):

```
As shown by the example above, it is mostly a regular HTML document, with few placeholders which needs to be replaced during export, an html ``<canvas>`` element, and some simple JavaScript code that calls the :js:class:`Engine` class.
```

```
``$GODOT_URL``: The name of the main JavaScript file, which provides the :js:class:`Engine` class required to start the engine and that must be included in the HTML as a ``<script>``. The name is generated from the *Export Path* during the export process.
```

```
The following optional placeholders will enable some extra features in your cusstom HTML template.
```

```
In case your project needs to have special control over the start arguments and dependency files, the :js:meth:`engine.start <Engine.prototype.start>` method can be used instead. Note, that this method do not automatically preload the ``pck`` file, so you will probably want to manually preload it (and any other extra file) via the :js:meth:`engine.preloadFile <Engine.prototype.preloadFile>` method.
```

Most are from the JS reference page and use a lot of markup which may have confused Weblate?

I'll report an issue upstream to debug further.

**Comment by magian1127** [comment]
@akien-mga 
All entries have been translated, can we update these pages in advance?
https://docs.godotengine.org/zh_CN/stable/

**Comment by timothyqiu** [comment]
It seems that the numbers have been fixed now. Could the doc website be updated so that pages like [this](https://docs.godotengine.org/zh_CN/stable/tutorials/inputs/controllers_gamepads_joysticks.html) is shown translated?
