### ISSUE TITLE
String replacement in property name processor breaks translation lookup

### ISSUE THREAD

**Issue by Cerno-b** [godotengine/godot-docs-l10n#23]
In the `editor_property_name_processor.cpp`, there are some property substrings that are automatically modified for display in Godot's settings. Unfortunately, this replacement seems to break translation lookup.

Case in point: 

* property: `low_processor_mode_sleep_usec`
* name in Weblate: `Low Processor Mode Sleep Usec`
* name processor rule: `capitalize_string_remaps["usec"] = U"(µsec)"; // Unit.`
* name displayed in the editor in English: `Low Processor Mode Sleep (µsec)`

I assume that since the name gets modified from `Usec` to `µsec`, it can't be found by the translation and will remain untranslated.

![image](https://github.com/godotengine/godot-docs-l10n/assets/16470072/40e5cea8-0e4e-4c6c-8feb-169ddfc18ac6)

**Comment by timothyqiu** [comment]
It was because our code style was changed from using `String::utf8("XXX")` to `U"XXX"`, but the extraction script did not catch that.

This is fixed in https://github.com/godotengine/godot-editor-l10n/pull/10. Weblate will be fixed on next sync.

**Comment by Cerno-b** [comment]
Nice!
