### ISSUE TITLE
[Chinese translation]VisibilityNotifier2D is missing in Godot 4.3, replaced by VisibleOnScreenNotifier2D?

### ISSUE THREAD

**Issue by zyox123cc** [godotengine/godot-docs-l10n#31]
In Godot 4.3, I noticed that `VisibilityNotifier2D` is no longer available. It seems to have been replaced by `VisibleOnScreenNotifier2D`. 

Is there any official documentation that highlights this change? I believe this might confuse users upgrading from previous versions of Godot, as it’s a significant change in node naming and functionality. It would be helpful to have this explicitly mentioned in the documentation or upgrade guides.

Would appreciate any clarification or confirmation on this change.

**Comment by timothyqiu** [comment]
It's on the [Upgrading from Godot 3 to Godot 4](https://docs.godotengine.org/en/stable/tutorials/migrating/upgrading_to_godot_4.html) page.

**Comment by Calinou** [comment]
Closing per the above comment.
