### ISSUE TITLE
Enabling localization of images

### ISSUE THREAD

**Issue by binotaliu** [godotengine/godot-docs-l10n#5]
There are several images used to describe concepts in the tutorial. I'd like to translate them. Can this be achived?

----

**Edited with an example:**

For this page: https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing_continued.html
![image](https://user-images.githubusercontent.com/59665613/83488202-f7a6a080-a49b-11ea-8a80-31b0f6075b62.png)

I have to use text to describe every single words in the diagrams for people who don't understand English like this:

https://hosted.weblate.org/translate/godot-engine/godot-docs/zh_Hant/?checksum=fa61799deff065f3

**Comment by akien-mga** [comment]
This is possible with Sphinx yes, though we won't be able to do it through Weblate a priori.

Sphinx supports automatically substituting images by localized ones if they use the format `{name}.{lang}{ext}`, e.g. `img/shooter_instancing.png` would be `img/shooter_instancing.zh_CN.png`.

I couldn't find the documentation for this but there's documentation for a config option that allows us to override that default format: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-figure_language_filename

But I think the default one might be a good fit for us as we already have separate `img/` subfolders in all folders, so splitting further might not be relevant. Unless we want to host images in this repo (https://github.com/godotengine/godot-docs-l10n) instead of https://github.com/godotengine/godot-docs, in which case we'd use that option to define a custom folder structure.

CC @mhilbrunner @NathanLovato

**Comment by binotaliu** [comment]
If possible we can use SVG for diagrams, then somehow put it into `*.po` files.

**Comment by akien-mga** [comment]
I think that's too technical to ask translators to copy a plain-text SVG, edit it, and then copy back the edited plain-text SVG.

But even then, `sphinx-intl` which generates the `.pot` files does not take SVG files into account, so I don't see an easy way to do this. And even then there are hundreds of files which do not make sense to have as vector graphic (e.g. editor screenshots), so that would only be a partial solution.

I think it's better to use actual files for both `.svg`, `.png` and `.jpg` files for consistency.

**Comment by akien-mga** [comment]
I did a test with building the French docs with `getting_started/step_by_step/img/shooter_instancing.fr.png` and I confirm that it works fine, the localized image is used.

I checked how to use https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-figure_language_filename to try to convert the path to point to files in `godot-docs-l10n` (with `figure_language_filename = "../img/{root}.{language}{ext}"`), but it doesn't work as the provided `{root}` component is the relative path using the `.. image::` directive, e.g. `img/shooter_instancing.png`, it doesn't contain the full path from the root folder.

So I guess we'll have to host all localized images in the main `godot-docs` repository, even though I'd have preferred to keep everything localization-related in `godot-docs-l10n`.

**Comment by akien-mga** [comment]
Relevant documentation on internationalization features: https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-internationalization

**Comment by binotaliu** [comment]
I think it's possible to put them in `godot-docs-l10n` by pointing  `figure_language_filename` to parent directory, just like `locale_dir`:

```python
figure_language_filename = "../images/{language}/{path}/{basename}{ext}"
```

**Comment by akien-mga** [comment]
That's what I tried but it doesn't seem to work.

Debugging Sphinx itself in `util/i18n.py::get_image_filename_for_language`, it seems that `{root}` (and `{path}`) are actually absolute:
```
root: /home/akien/Projects/godot/godot-docs-l10n/docs/tutorials/shading/img/vs_popup
path: /home/akien/Projects/godot/godot-docs-l10n/docs/tutorials/shading/img/
```

So it seems there's no way to keep the localized images out of tree, we'll have to include them all in `godot-docs`.

**Comment by akien-mga** [comment]
So the one thing that we can customize is to use a subfolder for localized images in each `img/` folder, i.e.
```
figure_language_filename = "{path}/{language}/{basename}{ext}"
```

So we'd have:
```
getting_started/step_by_step/img/shooter_instancing.png
getting_started/step_by_step/img/fr/shooter_instancing.png
getting_started/step_by_step/img/zh_CN/shooter_instancing.png
```

Instead of:
```
getting_started/step_by_step/img/fr/shooter_instancing.png
getting_started/step_by_step/img/fr/shooter_instancing.fr.png
getting_started/step_by_step/img/fr/shooter_instancing.zh_CN.png
```

I don't have a strong opinion either way. I guess the subfolder version can be useful if we have tons of images in a given `img/` folder, but I think so far with the per-section split it stays reasonable.

Having them all in the same folder with the same basename makes it easy to see which files need to be updated when changing the base English image.

**Comment by akien-mga** [comment]
I opened an issue upstream but even if a solution is implemented to support this use case, it would be quite a long way before we get it available on ReadTheDocs, as they still force using Sphinx 1.8.5 or earlier as their theme does not support newer Sphinx versions: https://github.com/readthedocs/readthedocs.org/blob/master/requirements/pip.txt#L12-L15
(which makes my upstream feature request a bit awkward, but AFAICT it's still relevant on the latest Sphinx code)

So let's go with having all localized screenshots in [godot-docs](https://github.com/godotengine/godot-docs) directly. The size of the repo will significantly increase for all documentation contributors, but I can't think of any workaround (aside from using a forked version of Sphinx, which I definitely don't want).

**Comment by binotaliu** [comment]
`get_image_filename_for_language` called `.format` method on `env.config.figure_language_filename`:
https://github.com/sphinx-doc/sphinx/blob/c063c9c0fe383a20da613448d1f606b9635773b9/sphinx/util/i18n.py#L313

So I tried to do a little hack, to make our own `format` method:

```python

current_dir = os.path.dirname(os.path.realpath(__file__))
locale_image_base_path = os.path.abspath('../images/{language}')

class CustomFormatter:
    def format(**args):
        path = args['path'].replace(current_dir, locale_image_base_path)
        args['path'] = path.format(**args)
        retval = "{path}{basename}{ext}".format(**args)
        print('formatted:')
        print(retval)
        return retval

figure_language_filename = CustomFormatter
```

Then it works fine to read on the parent directory.

(Sorry for my dirty code ;P, I haven't use Python before.)

**Comment by akien-mga** [comment]
Haha that's a brilliant hack, I wouldn't have thought of that. That might well be the best solution.

I was just working on my own hack symlinking all localized images to the default location expected by Sphinx, which seems to work fine too (on Linux at least, which I assume is what ReadTheDocs runs on):
```diff
diff --git a/conf.py b/conf.py
index 24def6f1..717646ce 100644
--- a/conf.py
+++ b/conf.py
@@ -181,9 +181,32 @@ linkcheck_timeout = 10
 
 # -- I18n settings --------------------------------------------------------
 
+# Godot localization is handled via https://github.com/godotengine/godot-docs-l10n
+# where the main docs repo is a submodule. Therefore the translated material is
+# actually in the parent folder of this conf.py, hence the "../".
+
 locale_dirs = ["../sphinx/po/"]
 gettext_compact = False
 
+# We want to host the localized images in godot-docs-l10n, but Sphinx does not provide
+# the necessary feature to do so. `figure_language_filename` has `{root}` and `{path}`,
+# but they resolve to (host) absolute paths, so we can't work with them.
+# What we do instead is that we add symlinks to the localized images in the location
+# where `figure_language_filename` expects them (keeping the default naming scheme).
+figure_language_filename = "{root}.{language}{ext}"
+
+# Here comes the ugly image symlinking logic.
+# We're running from conf.py's base dir so we symlink from `../img/` to `.`.
+localized_img_dir = "../img/"
+for root, dirs, files in os.walk(localized_img_dir):
+    for filename in files:
+        srcpath = os.path.abspath(os.path.join(root, filename))
+        dstpath = os.path.relpath(srcpath, localized_img_dir)
+        try:
+            os.symlink(srcpath, dstpath)
+        except FileExistsError:
+            pass
+
 # Couldn't find a way to retrieve variables nor do advanced string
 # concat from reST, so had to hardcode this in the "epilog" added to
 # all pages. This is used in index.rst to display the Weblate badge.
```

**Comment by groud** [comment]
I have just tested something, but apparently in python you can easily override a class's function, so something like this might work:
```
sphinx.util.i18n.get_image_filename_for_language = def get_image_filename_for_language(filename: str, env: "BuildEnvironment") -> str:
   # Your custom code for the function...
   pass
```
IMHO, it's a little bit cleaner than creating a new class overriding `format()`.

**Comment by akien-mga** [comment]
Gotta love Python for its hackability :D

`some_func = def new_func` gave me a syntax error with Python 3.8, but defining the function first seems to work:
```
import sphinx
sphinx_original_get_image_filename_for_language = sphinx.util.i18n.get_image_filename_for_language
cwd = os.getcwd()

def godot_get_image_filename_for_language(filename: str, env: "BuildEnvironment") -> str:
    path = sphinx_original_get_image_filename_for_language(filename, env)
    return os.path.join("../images/", os.path.relpath(path, cwd))

sphinx.util.i18n.get_image_filename_for_language = godot_get_image_filename_for_language
```

**Comment by sachin-suresh-rapyuta** [comment]
> ```diff
> localized_img_dir
> ```

Can anyone please help me with the code that I need to put in conf.py? I am trying to find a way to use the `figure_language_filename` option. But somehow its killing my time without results. Where do I put the customized code ? Sorry I am new to Python.. 


This is my conf.py:

```
figure_language_filename = "{root}.{language}{ext}"

sphinx_original_get_image_filename_for_language = sphinx.util.i18n.get_image_filename_for_language

def custom_get_image_filename_for_language(filename, env):
    """
    Hack the absolute path returned by Sphinx based on `figure_language_filename`
    to insert our `../images` relative path to godot-docs-l10n's images folder,
    which mirrors the folder structure of the docs repository.
    The returned string should also be absolute so that `os.path.exists` can properly
    resolve it when trying to concatenate with the original doc folder.
    """
    path = sphinx_original_get_image_filename_for_language(filename, env)
    path = os.path.abspath(os.path.join("../images/", os.path.relpath(path, cwd)))
    return path

sphinx.util.i18n.get_image_filename_for_language = custom_get_image_filename_for_language
```

When I run: `sphinx-intl update -p build/gettext -l ja`, I get: 

```
File "conf.py", line 106, in <module>
    sphinx_original_get_image_filename_for_language = sphinx.util.i18n.get_image_filename_for_language
AttributeError: module 'sphinx.util' has no attribute 'i18n'
```
